In [10]:
output_path = "../results/day29_tuned_model_verification.csv"

tuned_verification.to_csv(output_path, index=False)

print(f"Saved: {output_path}")
print(f"Rows: {len(tuned_verification)}")
print(f"Columns: {len(tuned_verification.columns)}")

Saved: ../results/day29_tuned_model_verification.csv
Rows: 5
Columns: 5

In [9]:
metric_columns = ["Accuracy", "Precision", "Recall", "F1 Score"]

print("Missing values:")
print(tuned_verification[metric_columns].isnull().sum())

print("\nMetric range check:")
for metric in metric_columns:
    print(
        f"{metric}: "
        f"min={tuned_verification[metric].min():.6f}, "
        f"max={tuned_verification[metric].max():.6f}"
    )

print("\nModel count:", tuned_verification["Model"].nunique())
print("Duplicate rows:", tuned_verification.duplicated().sum())

Missing values:
Accuracy     0
Precision    0
Recall       0
F1 Score     0
dtype: int64

Metric range check:
Accuracy: min=0.998101, max=0.999637
Precision: min=0.998167, max=0.999825
Recall: min=0.990037, max=0.999447
F1 Score: min=0.994907, max=0.999032

Model count: 5
Duplicate rows: 0

In [6]:
verification_rows = []

results = [
    ("XGBoost", xgb_result),
    ("LightGBM", lgbm_result),
    ("Random Forest", rf_result),
    ("Decision Tree", dt_result),
    ("AdaBoost", ada_result),
]

for model_name, df in results:
    row = df.iloc[-1].copy()
    row["Model"] = model_name
    verification_rows.append(row)

tuned_verification = pd.DataFrame(verification_rows)

print("Tuned Model Verification:")
display(tuned_verification)

Tuned Model Verification:

           Model  Accuracy  Precision    Recall  F1 Score
1        XGBoost  0.999637   0.998617  0.999447  0.999032
1       LightGBM  0.999611   0.998652  0.999274  0.998963
1  Random Forest  0.999378   0.998167  0.998512  0.998340
1  Decision Tree  0.999520   0.998479  0.998962  0.998720
1       AdaBoost  0.998101   0.999825  0.990037  0.994907

In [5]:
xgb_result = pd.read_csv("../results/day25_xgboost_tuning_results.csv")
lgbm_result = pd.read_csv("../results/day26_lightgbm_tuning_results.csv")
rf_result = pd.read_csv("../results/day27_random_forest_tuning_results.csv")
dt_result = pd.read_csv("../results/day28_decision_tree_tuning_results.csv")
ada_result = pd.read_csv("../results/day28_adaboost_tuning_results.csv")

print("XGBoost:")
display(xgb_result)

print("\nLightGBM:")
display(lgbm_result)

print("\nRandom Forest:")
display(rf_result)

print("\nDecision Tree:")
display(dt_result)

print("\nAdaBoost:")
display(ada_result)

XGBoost:

              Model  Accuracy  Precision    Recall  F1 Score
0  XGBoost Baseline  0.999637   0.999637  0.999637  0.999637
1     XGBoost Tuned  0.999637   0.998617  0.999447  0.999032

LightGBM:

               Model  Accuracy  Precision    Recall  F1 Score
0  LightGBM Baseline  0.999663   0.999663  0.999663  0.999663
1     LightGBM Tuned  0.999611   0.998652  0.999274  0.998963

Random Forest:

                    Model  Accuracy  Precision    Recall  F1 Score
0  Random Forest Baseline  0.999261   0.999261  0.999261  0.999261
1     Random Forest Tuned  0.999378   0.998167  0.998512  0.998340

Decision Tree:

                    Model  Accuracy  Precision    Recall  F1 Score
0  Decision Tree Baseline   0.99941   0.999410  0.999410   0.99941
1     Decision Tree Tuned   0.99952   0.998479  0.998962   0.99872

AdaBoost:

               Model  Accuracy  Precision    Recall  F1 Score
0  AdaBoost Baseline  0.997583   0.997584  0.997583  0.997579
1     AdaBoost Tuned  0.998101   0.999825  0.990037  0.994907

In [4]:
import os

files_to_check = [
    "../results/day25_xgboost_tuning_results.csv",
    "../results/day26_lightgbm_tuning_results.csv",
    "../results/day27_random_forest_tuning_results.csv",
    "../results/day28_decision_tree_tuning_results.csv",
    "../results/day28_adaboost_tuning_results.csv",
]

for file_path in files_to_check:
    print(os.path.basename(file_path), "->", os.path.exists(file_path))

day25_xgboost_tuning_results.csv -> True
day26_lightgbm_tuning_results.csv -> True
day27_random_forest_tuning_results.csv -> True
day28_decision_tree_tuning_results.csv -> True
day28_adaboost_tuning_results.csv -> True

In [2]:
X_train = pd.read_csv("../data/X_train_final.csv")
X_test = pd.read_csv("../data/X_test_final.csv")
y_train = pd.read_csv("../data/y_train_final.csv").squeeze("columns")
y_test = pd.read_csv("../data/y_test_final.csv").squeeze("columns")

print("X_train:", X_train.shape)
print("X_test :", X_test.shape)
print("y_train:", y_train.shape)
print("y_test :", y_test.shape)

X_train: (617269, 58)
X_test : (154318, 58)
y_train: (617269,)
y_test : (154318,)

In [1]:
import pandas as pd
import numpy as np
import joblib
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score